runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2

#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
#[END_EXCLUDE]

handlers:
# The endpoints handler must be mapped to /_ah/api.
#- url: /_ah/api/.*
#  script: main.api

- url: /barcode_info.*
  script: barcode.app

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11
- name: lxml
  version: 3.7.3
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"  
- name: pytz
  version: "2016.4"

# [START env_vars]
env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  #  ENDPOINTS_SERVICE_NAME: project20180407.appspot.com
  # ENDPOINTS_SERVICE_VERSION: 2018-04-10r2
 # [END env_vars]
